"""Check an actual wheel's Windows path budget; optionally install it on Windows.

Run directly with a build Python, not an editable govkit interpreter. This script
uses only the standard library so the install environment starts with no govkit.
"""

import argparse
import json
import subprocess
import sys
import tempfile
import venv
import zipfile
from pathlib import Path, PurePosixPath

# Issue #129 reproduced a 270-character installed path. A 124-character venv
# exercises that failure with the original 128-character wheel member (271).
# Windows MAX_PATH includes the terminating NUL: 124 + 19 + 116 + 1 = 260.
VENV_PATH_LENGTH = 124
MEMBER_BUDGET = 259 - VENV_PATH_LENGTH - len("\\Lib\\site-packages\\")


def windows_length(value: str) -> int:
    return len(value.encode("utf-16-le")) // 2


def check_wheel(wheel: Path) -> None:
    """Reject oversized payloads and their generated bytecode before installation."""
    with zipfile.ZipFile(wheel) as archive:
        members = [item.filename for item in archive.infolist() if not item.is_dir()]
    if not members:
        raise ValueError("Wheel contains no files")
    installed = list(members)
    for member in members:
        if member.endswith(".py"):
            source = PurePosixPath(member)
            for tag in ("cpython-311", "cpython-312"):
                installed.append(str(source.parent / "__pycache__" / f"{source.stem}.{tag}.pyc"))
    oversized = [name for name in installed if windows_length(name) > MEMBER_BUDGET]
    if oversized:
        details = "\n".join(f"  {windows_length(name)}: {name}" for name in oversized)
        raise ValueError(
            f"Wheel exceeds the {MEMBER_BUDGET}-character Windows member budget "
            f"for a {VENV_PATH_LENGTH}-character virtualenv:\n{details}"
        )
    longest = max(installed, key=windows_length)
    print(f"Windows wheel path budget: {windows_length(longest)}/{MEMBER_BUDGET}: {longest}")


def windows_install(wheel: Path) -> None:
    """Exercise pip and both pack catalogs with legacy Windows limits enabled."""
    if sys.platform != "win32":
        raise RuntimeError("--install requires Windows; a simulated path check is not an install")
    import winreg

    with winreg.OpenKey(
        winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\FileSystem"
    ) as key:
        enabled, _ = winreg.QueryValueEx(key, "LongPathsEnabled")
    if enabled != 0:
        raise RuntimeError("The Windows install regression requires LongPathsEnabled=0")

    with tempfile.TemporaryDirectory(prefix="govkit-win-") as temporary:
        root = Path(temporary).resolve()
        padding = VENV_PATH_LENGTH - windows_length(str(root)) - 1
        if padding < 1:
            raise RuntimeError("Temporary root is too long for the declared virtualenv fixture")
        environment = root / ("v" * padding)
        environment.mkdir()
        assert windows_length(str(environment)) == VENV_PATH_LENGTH

        # Prove the new process actually enforces the setting. An enabled runner
        # would otherwise make the original broken wheel pass this regression.
        probe = environment / ("x" * (260 - VENV_PATH_LENGTH - 1))
        try:
            probe.write_bytes(b"limit probe")
        except OSError as exc:
            if exc.winerror not in (2, 3, 206):
                raise
        else:
            probe.unlink()
            raise RuntimeError("The 260-character probe unexpectedly succeeded")

        venv.EnvBuilder(with_pip=True).create(environment)
        python = environment / "Scripts/python.exe"
        command = [str(python), "-I"]
        subprocess.run(command + ["-m", "pip", "install", str(wheel)], check=True)
        subprocess.run(command + ["-m", "pip", "check"], check=True)
        # Native entrypoint, not only python -m, must exist after the pip install.
        subprocess.run([str(environment / "Scripts/govkit.exe"), "--help"], check=True)
        inspection = subprocess.run(
            command
            + [
                "-c",
                "import json, sys; from pathlib import Path; from cli import paths, pack_loading; "
                "assert Path(pack_loading.__file__).is_relative_to(sys.prefix); "
                "assert paths.EXTENSION_PACKS_DIR.is_relative_to(sys.prefix); "
                "print(json.dumps([p.id for p in pack_loading.bundled_catalog()]))",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        with zipfile.ZipFile(wheel) as archive:
            pack_prefix = "cli/ext/"
            expected = {
                name.removeprefix(pack_prefix).split("/")[0]
                for name in archive.namelist()
                if name.startswith(pack_prefix) and name.endswith("/manifest.yaml")
            }
            assert expected, "Wheel must contain extension packs"
            assert set(json.loads(inspection.stdout)) == expected
            target = root / "consumer"
            target.mkdir()
            subprocess.run(
                command
                + [
                    "-m",
                    "cli.govkit",
                    "extension",
                    "add",
                    "skill-oriented-agent-architecture",
                    "--target",
                    str(target),
                ],
                check=True,
            )
            prefix = pack_prefix + "skill-oriented-agent-architecture/"
            for name in archive.namelist():
                if name.startswith(prefix) and not name.endswith("/"):
                    installed = target / "extensions" / name.removeprefix(pack_prefix)
                    assert installed.read_bytes() == archive.read(name), installed
        print(
            f"Windows deep install passed: virtualenv length={VENV_PATH_LENGTH}; packs={len(expected)}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wheel", type=Path)
    parser.add_argument("--install", action="store_true")
    args = parser.parse_args()
    wheel = args.wheel.resolve(strict=True)
    check_wheel(wheel)
    if args.install:
        windows_install(wheel)


if __name__ == "__main__":
    main()
