<#
.SYNOPSIS
  Smoke-tests govkit across the agent x level x UI-framework matrix.

.DESCRIPTION
  Parallel to smoke.ps1 but exercises the --ui dimension. For each
  (agent, framework, level) combination, creates a fresh sandbox, runs
  `govkit apply --ui <framework>`, drops in the 3 spec inputs
  (acceptance.feature, nfrs.md, eval_criteria.yaml) of a minimal
  hello_world_ui feature for L4+, and runs `govkit validate`.

  L3: validate short-circuits (no per-feature artifacts). The apply itself
      is what proves the UI dimension is wired up correctly at this level.
  L4: validate is expected to FAIL. The smoke feature ships only the 3 spec
      inputs; plan.md and architecture_preflight.md must be generated by
      invoking /ui-architecture-preflight and /ui-spec-planning in the agent.
  L5: validate also expected to fail (missing artifacts plus mode is not llm).

.PARAMETER SandboxRoot
  Where the per-config project folders are created. Default: this script's directory.
  Override with -SandboxRoot to redirect output elsewhere (e.g. an external sandbox dir).

.PARAMETER RepoPath
  Path to the governed-ai-delivery repo (editable install source).
  Default: parent of this script's directory (i.e. the repo root when run from scripts/).

.PARAMETER Agents
  Agents to test. Default: all three (claude-code, codex, copilot).

.PARAMETER Frameworks
  UI frameworks to test. Default: react, angular.

.PARAMETER Levels
  Levels to test. Default: 3, 4, 5.

.PARAMETER Force
  Delete existing sandbox folders before recreating.

.EXAMPLE
  .\smoke-ui.ps1
  .\smoke-ui.ps1 -Agents claude-code -Frameworks react -Levels 4 -Force
  .\smoke-ui.ps1 -SandboxRoot c:\users\marty\source\sandbox\govkit-test
#>

[CmdletBinding()]
param(
    [string]$SandboxRoot  = $PSScriptRoot,
    [string]$RepoPath     = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string[]]$Agents     = @("claude-code", "codex", "copilot"),
    [string[]]$Frameworks = @("react", "angular"),
    [string[]]$Levels     = @("3", "4", "5"),
    [switch]$Force
)

$ErrorActionPreference = "Stop"

# ----------------------------------------------------------------------------
# venv bootstrap (shares the same .venv as smoke.ps1)
# ----------------------------------------------------------------------------

$venvDir    = Join-Path $SandboxRoot ".venv"
$venvPython = Join-Path $venvDir "Scripts\python.exe"
$venvGovkit = Join-Path $venvDir "Scripts\govkit.exe"

if (-not (Test-Path $venvPython)) {
    Write-Host "Creating venv at $venvDir" -ForegroundColor Cyan
    python -m venv $venvDir
}

if (-not (Test-Path $venvGovkit)) {
    Write-Host "Installing govkit (editable) from $RepoPath" -ForegroundColor Cyan
    & $venvPython -m pip install --quiet --upgrade pip
    & $venvPython -m pip install --quiet -e $RepoPath
}

$installedVersion = (& $venvPython -c "from importlib.metadata import version; print(version('govkit'))").Trim()
Write-Host "govkit version: $installedVersion" -ForegroundColor Cyan
Write-Host ""

$env:GOVKIT_NO_MIGRATION_WARNING = "1"

# ----------------------------------------------------------------------------
# hello_world_ui feature content (L4 smoke feature)
#
# Tags chosen to satisfy validate.py:
#   - @e2e on every user-facing scenario (UI convention)
#   - @nfr-performance to cover the one populated NFR category
#
# NFR categories deliberately limited to ## Performance because
# check_gherkin_nfr_coverage only enforces tags for categories present in
# its category_to_tag map. Accessibility / Browser Compatibility / Usability
# are not in that map, so they are not part of this smoke check.
# ----------------------------------------------------------------------------

$featureAcceptance = @'
Feature: Hello World UI Card

  As a developer smoke-testing the govkit install
  I want a minimal greeting card on a page
  So that I can confirm UI scaffolding and validation work end to end

  @e2e
  Scenario: Render the default greeting
    Given the hello card page is loaded
    When the page finishes rendering
    Then the card displays the text "hello, world"

  @e2e @nfr-performance
  Scenario: Page meets the LCP target on a standard connection
    Given the hello card page is loaded on a standard 4G profile
    When Core Web Vitals are measured
    Then Largest Contentful Paint is below 2500ms
'@

$featureNfrs = @'
# Non-Functional Requirements: Hello World UI Card

## Repository Scope

**Scope:** `single-repo`

## Performance
- The hello card page must achieve Largest Contentful Paint under 2500ms on a standard 4G profile
'@

$featureEval = @'
version: 1
feature: hello_world_ui
mode: deterministic
owner: smoke-test

unit_tests:
  enforce_FIRST: true
  minimum_FIRST_average: 4

code_quality:
  enforce_virtues: true
  minimum_virtue_average: 4
'@

function Write-HelloUiFeature {
    param([string]$ProjectRoot)
    $dir = Join-Path $ProjectRoot "features\hello_world_ui"
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
    Set-Content -Path (Join-Path $dir "acceptance.feature") -Value $featureAcceptance -Encoding utf8
    Set-Content -Path (Join-Path $dir "nfrs.md")            -Value $featureNfrs       -Encoding utf8
    Set-Content -Path (Join-Path $dir "eval_criteria.yaml") -Value $featureEval       -Encoding utf8
}

# ----------------------------------------------------------------------------
# Matrix runner
# ----------------------------------------------------------------------------

$projectsRoot = Join-Path $SandboxRoot "projects-ui"
New-Item -ItemType Directory -Path $projectsRoot -Force | Out-Null

$results = @()

foreach ($agent in $Agents) {
    foreach ($framework in $Frameworks) {
        foreach ($level in $Levels) {
            $name        = "$agent-$framework-l$level"
            $projectPath = Join-Path $projectsRoot $name

            Write-Host "================================================================" -ForegroundColor Yellow
            Write-Host " $name" -ForegroundColor Yellow
            Write-Host "================================================================" -ForegroundColor Yellow

            if (Test-Path $projectPath) {
                if ($Force) {
                    Write-Host "  removing existing $projectPath" -ForegroundColor DarkGray
                    Remove-Item -Recurse -Force $projectPath
                } else {
                    Write-Host "  SKIP -- already exists (use -Force to recreate)" -ForegroundColor DarkYellow
                    $results += [pscustomobject]@{ Config = $name; Apply = "skip"; Validate = "skip" }
                    continue
                }
            }
            New-Item -ItemType Directory -Path $projectPath -Force | Out-Null

            # ---- apply ----
            Write-Host "  govkit apply --agent $agent --level $level --ui $framework" -ForegroundColor Cyan
            & $venvGovkit apply --agent $agent --level $level --type api --ui $framework --ci github --target $projectPath
            $applyExit   = $LASTEXITCODE
            $applyStatus = if ($applyExit -eq 0) { "PASS" } else { "FAIL($applyExit)" }

            # ---- drop hello_world_ui for L4+ ----
            if ($applyExit -eq 0 -and $level -ne "3") {
                Write-Host "  writing features/hello_world_ui/" -ForegroundColor Cyan
                Write-HelloUiFeature -ProjectRoot $projectPath
            }

            # ---- validate ----
            Write-Host "  govkit validate --level $level" -ForegroundColor Cyan
            & $venvGovkit validate --target $projectPath --level $level
            $validateExit   = $LASTEXITCODE
            $validateStatus = if ($validateExit -eq 0) { "PASS" } else { "FAIL($validateExit)" }

            $results += [pscustomobject]@{
                Config   = $name
                Apply    = $applyStatus
                Validate = $validateStatus
            }
            Write-Host ""
        }
    }
}

# ----------------------------------------------------------------------------
# Summary
# ----------------------------------------------------------------------------

Write-Host "================================================================" -ForegroundColor Green
Write-Host " UI Summary" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
$results | Format-Table -AutoSize

$failed = $results | Where-Object {
    $_.Apply -like "FAIL*" -or
    ($_.Validate -like "FAIL*" -and $_.Config -notlike "*-l4" -and $_.Config -notlike "*-l5")
}
if ($failed) {
    Write-Host "Some configs failed (L4/L5 validate-fails are expected; only L3 validate must pass)." -ForegroundColor Red
    exit 1
}
Write-Host "All apply steps and L3 validate passed. L4/L5 validate are expected to fail until /ui-architecture-preflight and /ui-spec-planning generate the missing artifacts." -ForegroundColor Green
exit 0
